### ISSUE TITLE
Tag released versions

### ISSUE THREAD

**Issue by IanLee1521** [dhs-ncats/pshtt#111]
We should make sure to tag the released versions in the git repo to ensure we know what has gotten released.

For instance, do we know for sure what commit s responsible for: https://pypi.python.org/pypi/pshtt/0.2.3 ?

**Comment by jsf9k** [comment]
TravisCI is now automatically deploying to PyPI and Docker Hub when the repo is tagged.  (The version information comes from the file `pshtt/__init__.py`.)  This resolves this issue.

I've also added some helper scripts in the root directory of the project for bumping versions and tagging.  These are `bump_version.sh` and `tag.sh`, respectively.

**Comment by IanLee1521** [comment]
That is so cool! I didn't realize there was a `semver` package.

One... Question...? With a lot of these things, I like to make the `git push` a separate (manual) action, e.g. https://github.com/dhs-ncats/pshtt/blob/c3a0d360660c7d6a4ecab8ecf54e5a69acb44d0b/bump_version.sh#L22 

-- Thoughts?

That way I can go back and fix it up if I did something accidentally.

**Comment by jsf9k** [comment]
I only thought to look for such a package because I've used [this `semver` package](https://www.npmjs.com/package/semver) in the past when working with `npm`.

I first had `bump_version.sh` without the `git push`, for the very reason you mention, but I quickly got tired of having to do the separate manual push step.  I think there's an argument for doing it either way.

Since I intend to make similar changes to `trustymail`, do you mind giving the `pshtt` `setup.py` and `setup.cfg` files a look and making sure there is nothing we want to add or tidy up there?  (You're more experienced in Python packaging than I am.)

Incidentally, it's pretty cool that the new PyPI website supports markdown syntax.  [I was able to just read in our `README.md` and use it as the `long_description`](https://pypi.org/project/pshtt/0.4.2rc9/).

**Comment by IanLee1521** [comment]
Sure thing! I'll take a look today or over the weekend.

And yes, that Markdown support is awesome. I'd been following that conversation / ticket / feature request for a long time. This will be the first time I've seen it used. :)
