### ISSUE TITLE
Redirecting to External Sites Causes Non-Compliance

### ISSUE THREAD

**Issue by climber-girl** [dhs-ncats/pshtt#216]
# 🐛 Summary #

Why should domains have to redirect immediately to another site in the same domain?  Don't the following ring true as compliant with BOD 18-01?

a) if HTTP, must redirect using code in the 300s to a location of https:// (regardless of whether on the same domain)
b) if HTTP, HTTPS of domain must be supported (regardless of if HTTP status code)
c) HTTPS must have strong HSTS with a max-age of at least 31536000
note: if HTTP-www, same as above substituting HTTP with HTTP-www and HTTPS with HTTPS-www

It seems that some domains that redirect to an external resource are not counted as in compliance, which I believe should be fine as long as redirects are always to an HTTPS endpoint.

## To reproduce ##

Consider `careers-int.llnl.gov`.  Pshtt shows it as compliant only with the Supports HTTPS and Strong HSTS requirements, but not with the Enforces HTTPS requirement.  This is because "Enforces HTTPS" is determined here:
https://github.com/cisagov/pshtt/blob/develop/pshtt/pshtt.py#L1336-L1346.

- `is_domain_supports_https(domain)` and `is_strictly_forces_https(domain)` are both `True` in this case.
-  `is_http_redirect_domain(domain)` is `False`...  This is not considered a "redirect domain" since the redirect eventually comes back inside llnl.gov (after first going to smartrecruiters.com).
-  `is_defaults_to_https(domain)` is `False` because the "canonical domain" (determined here: https://github.com/cisagov/pshtt/blob/develop/pshtt/pshtt.py#L774-L884) ends up being the http:// URL.  See in particular here:  https://github.com/cisagov/pshtt/blob/develop/pshtt/pshtt.py#L869-L875, noting that `both_http_down` is `False`, as is `at_least_one_http_upgrades` since `redirect_immediately_to_external` is `True` for the http:// URL (even though it eventually redirects internally).

## Expected behavior ##

careers-int.llnl.gov should be considered compliant with Enforces HTTPS as it is redirecting using a code in the 300s, upgrading to HTTPS with the https:// location, and its HTTPS endpoint is not downgrading back to plain HTTP.

```$ curl --head careers-int.llnl.gov
HTTP/1.0 301 Moved Permanently
Strict-Transport-Security: max-age=31536000; includeSubDomains
Cache-Control: no-cache
Location: https://www.smartrecruiters.com/web-sso/saml/LLNL/login
Connection: close
Content-Length: 0

$ curl --head https://careers-int.llnl.gov
HTTP/1.0 301 Moved Permanently
Strict-Transport-Security: max-age=31536000; includeSubDomains
Cache-Control: no-cache
Location: https://www.smartrecruiters.com/web-sso/saml/LLNL/login
Connection: close
Content-Length: 0
```

## Recommendation ##

I believe reviewing the code in https://github.com/cisagov/pshtt/blob/59f2bb0b1d64a79adf13552c711c883771020178/pshtt/pshtt.py#L858-LL862 may help: 
```     
def http_upgrades(endpoint):
        return (
            endpoint.redirect_immediately_to_https and
            (not endpoint.redirect_immediately_to_external)
        )
```

Thoughts on getting rid of the "and (not endpoint.redirect_immediately_to_external)" part?  Any other suggestions?  Any compliance concerns with a redirect to an external site?

**Comment by climber-girl** [comment]
Looks like researchtoreality.cancer.gov may be in the same boat with respect to not being seen as compliant with "Enforces HTTPS" according to pshtt due to the external redirect. @h-m-f-t @jsf9k @konklone any thoughts?

```
$ curl --head researchtoreality.cancer.gov
HTTP/1.0 301 Moved Permanently
Location: https://go.usa.gov/xmqyV
Strict-Transport-Security: max-age=31536000; preload
Server: BigIP
Connection: Keep-Alive
Content-Length: 0

$ curl --head https://researchtoreality.cancer.gov
HTTP/1.0 301 Moved Permanently
Location: https://go.usa.gov/xmqyV
Strict-Transport-Security: max-age=31536000; preload
Server: BigIP
Connection: Keep-Alive
Content-Length: 0

$ curl --head www.researchtoreality.cancer.gov
HTTP/1.0 301 Moved Permanently
Location: https://go.usa.gov/xmqyV
Strict-Transport-Security: max-age=31536000; preload
Server: BigIP
Connection: Keep-Alive
Content-Length: 0

$ curl --head https://www.researchtoreality.cancer.gov
HTTP/1.0 301 Moved Permanently
Location: https://go.usa.gov/xmqyV
Strict-Transport-Security: max-age=31536000; preload
Server: BigIP
Connection: Keep-Alive
Content-Length: 0
```

**Comment by echudow** [comment]
I agree with you that [`Domain Enforces HTTPS`](https://github.com/cisagov/pshtt/blob/59f2bb0b1d64a79adf13552c711c883771020178/pshtt/pshtt.py#L1336) should be `True` for `http://researchtoreality.cancer.gov` due to all the redirects to `https://` addresses, and in this case it's incorrectly `False`.

However, I don't think [`http_upgrades(endpoint)`](https://github.com/cisagov/pshtt/blob/59f2bb0b1d64a79adf13552c711c883771020178/pshtt/pshtt.py#L858-LL862) is the issue. That function is used to figure out which endpoint is the [`canonical_endpoint`](https://github.com/cisagov/pshtt/blob/59f2bb0b1d64a79adf13552c711c883771020178/pshtt/pshtt.py#L774), which I think is correctly `http://researchtoreality.cancer.gov` for the example above (since that is logically the default endpoint of the four, especially if someone just typed `researchtoreality.cancer.gov` into a web browser (I don't think browsers have implemented checking `https://` first yet, but I could be mistaken)).

Instead, I think the issue actually is due to [`base_original = parent_domain_for(subdomain_original)`](https://github.com/cisagov/pshtt/blob/59f2bb0b1d64a79adf13552c711c883771020178/pshtt/pshtt.py#L451), [`base_eventual = parent_domain_for(subdomain_eventual)`](https://github.com/cisagov/pshtt/blob/59f2bb0b1d64a79adf13552c711c883771020178/pshtt/pshtt.py#L482), and [`endpoint.redirect_eventually_to_external = (base_original != base_eventual)`](https://github.com/cisagov/pshtt/blob/59f2bb0b1d64a79adf13552c711c883771020178/pshtt/pshtt.py#L487) that combine so that `endpoint.redirect_eventually_to_external` is `False` even though the eventual hostname is `cancercontrol.cancer.gov` and not `researchtoreality.cancer.gov`, so it really does redirect eventually to an external site.  I think the problem is that the code is assuming that it is only dealing with second-level domains and doesn't account for lower-level domains, like `researchtoreality.cancer.gov`.  In this case, I think the code at https://github.com/cisagov/pshtt/blob/59f2bb0b1d64a79adf13552c711c883771020178/pshtt/pshtt.py#L442-LL491 should be fixed to account for lower-level domains so that it correctly views redirects from `researchtoreality.cancer.gov` to `cancercontrol.cancer.gov` as an eventual external redirect.  Once that happens, then [`is_redirect(endpoint)`](https://github.com/cisagov/pshtt/blob/59f2bb0b1d64a79adf13552c711c883771020178/pshtt/pshtt.py#L947) will be `True`, in turn making [`is_http_redirect_domain(domain)`](https://github.com/cisagov/pshtt/blob/59f2bb0b1d64a79adf13552c711c883771020178/pshtt/pshtt.py#L972) `True`, and finally making [`is_domain_enforces_https(domain)`](https://github.com/cisagov/pshtt/blob/59f2bb0b1d64a79adf13552c711c883771020178/pshtt/pshtt.py#L1336) `True` for `researchtoreality.cancer.gov`.

Unfortunately though, this brings up a separate question about HSTS in that `Domain Uses Strong HSTS` is `True`, but the `canonical` endpoint is `http://researchtoreality.cancer.gov` that redirects to external sites, so in reality most browsers will never see the HSTS header.  In that case, HSTS is not adding any security since every time that a user browses to `researchtoreality.cancer.gov` it will be done to the regular unauthenticated and unencrypted `http://` without ever seeing the HSTS header and vulnerable to a malicious actor performing a man-in-the-middle of that connection every single time. Based on that, shouldn't `Domain Uses Strong HSTS` actually be `False`? For that, [`is_domain_strong_hsts(domain)`](https://github.com/cisagov/pshtt/blob/59f2bb0b1d64a79adf13552c711c883771020178/pshtt/pshtt.py#L1349) should make sure that the `http` endpoints are either down or redirect to or through an `https` endpoint at the same hostname with a strong HSTS header.

**Comment by climber-girl** [comment]
Thanks, @echudow!  I didn't even consider the ineffectiveness of the domain's HSTS header with this type of redirect behavior.  While technically, the domain serves strong HSTS, that directive to only use HTTPS would not be heeded since it wouldn't be seen in certain situations and, therefore, I get why this wouldn't be considered Enforces HTTPS.

Unless you, @h-m-f-t, @konklone, @jsf9k, @dav3r, or @mcdonnnj think we should change the logic, I'm happy to leave it as is for now, being able to explain why these domains aren't technically meeting the Enforces HTTPS requirement :)
