### ISSUE TITLE
HSTS subdomain detection happening at the root should be more explicit

### ISSUE THREAD

**Issue by garrettr** [dhs-ncats/pshtt#47]
The Guardian just deployed HSTS, and wanted to know why their score on Secure the News hadn't been updated yet. After a bit of digging, we realized the problem appears to be caused by a bug in pshtt.

Here's the relevant output from `pshtt --json theguardian.com`:

```json
[
  {
    "Base Domain": "theguardian.com", 
    "Canonical URL": "https://www.theguardian.com", 
    "Defaults to HTTPS": true, 
    "Domain": "theguardian.com", 
    "Downgrades HTTPS": false, 
    "HSTS": true, 
    "HSTS Entire Domain": null, 
    "HSTS Header": "max-age=31536000; includeSubDomains; preload", 
    "HSTS Max Age": 31536000, 
    "HSTS Preload Ready": null, 
    "HSTS Preloaded": false,
  }
]
```

As you can see, pshtt correctly parsed the `max-age` from the HSTS header, but failed to correctly parse `includeSubDomains` or `preload`, leading to incorrect results for `"HSTS Entire Domain"` and `"HSTS Preload Ready"`.

**Comment by garrettr** [comment]
I dug into this a bit more, and have verified that the HSTS parser is actually working correctly; this bug is actually caused by a confusing discrepancy in which endpoint a 

First of all, note that the Guardian is currently serving two _different_ HSTS policies: one on `theguardian.com` and a different one on `www.theguardian.com`.

```
$ curl -Is https://theguardian.com | grep Strict-Transport-Security
Strict-Transport-Security: max-age=31536000
$ curl -Is https://www.theguardian.com | grep Strict-Transport-Security
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

The discrepancy between `"HSTS Header"` and `"HSTS Entire Domain"`/`"HSTS Preload Ready"` is due to the fact that they are derived from different endpoints. Like most of the other top-level values in pshtt's output, `"HSTS Header`" and `"HSTS max-age"` are derived from the _canonical_ endpoint (as determined by pshtt). However, `"HSTS Entire Domain"`/`"HSTS Preload ready` are derived from the _root_ endpoint.

I can understand why these values are derived from different endpoints, but I do think it makes the output of pshtt very confusing in cases like this one. It certainly looks like a bug!

**Comment by h-m-f-t** [comment]
Thanks @garrettr. I really appreciate your work.

It does seem confusing that `HSTS Entire Domain` and `HSTS Preload Ready` report what's at the https root endpoint, but this is consistent with our intention of capturing how HSTS protects the entire domain. (These values are especially helpful when, e.g., we're hitting subdomains but not their parent domains.) We should make sure this is clear in the README.

In the case of the Guardian, throwing `includeSubDomains` on `www` will only protect subdomains of `www.theguardian.com`, which _isn't_ the entire domain and probably isn't their desired impact. Also, `preload` is only protective at the root domain; see [hstspreload.org](https://hstspreload.org), where the submission requirements to the preload list are spelled out:

> ...
> 4. Serve an HSTS header on the base domain for HTTPS requests

From my seat, it looks like The Guardian should probably use the `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload` directive on `theguardian.com`, instead of `www`, though it doesn't seem like a bad idea to, until the domain is preloaded, also include an HSTS header (non-`preload`, non-`includeSubDomains`) on `www.theguardian.com` for those who hit the `www` directly.

**Comment by konklone** [comment]
@garrettr - @h-m-f-t summed up the rationale for the current state pretty well, but to your point, if you have any suggestions for how we can make this more clear in the data output, that'd be welcome. It's still early in the tool's lifecycle and adoption, and probably still possible to make breaking changes.

**Comment by garrettr** [comment]
@h-m-f-t Thanks for the fantastic reply, very helpful!

 > From my seat, it looks like The Guardian should probably use the Strict-Transport-Security: max-age=31536000; includeSubDomains; preload directive on theguardian.com, instead of www, though it doesn't seem like a bad idea to, until the domain is preloaded, also include an HSTS header (non-preload, non-includeSubDomains) on www.theguardian.com for those who hit the www directly.

I agree, and will pass that recommendation along to folks at the Guardian!

> if you have any suggestions for how we can make this more clear in the data output, that'd be welcome

I think making it clearer in the README, as @h-m-f-t suggested, is good enough for now!

**Comment by konklone** [comment]
(Renamed the issue to make it more clear what the remaining action item is.)

**Comment by h-m-f-t** [comment]
I've updated the README to make it clear that `HSTS Entire Domain` and `HSTS Preload Ready` pull from the **root** HTTPS endpoint. Thanks @garrettr; feel free to reopen if additional clarity it needed.

**Comment by garrettr** [comment]
lgtm @h-m-f-t, thanks! that README change would've saved me a bit of confusion back when I first filed this issue :+1:
