### ISSUE TITLE
Change License to MIT?

### ISSUE THREAD

**Issue by IanLee1521** [dhs-ncats/pshtt#72]
Would it be possible to change the license for external (non-Federal Employee) contributions to an MIT (or other open source license)?

I've recently encountered an issue where @LLNL isn't able to allow me to contribute as part of my work due to the CC0 provisions around "waiving copyright", which it can't / won't do.

MIT is the license used in, at least, https://github.com/deptofdefense/anet which the lab is more amenable to contributing to.

**Comment by IanLee1521** [comment]
Any thoughts about this idea?

**Comment by IanLee1521** [comment]
Alternate suggestion from internal, would I be able to contribute code that was itself covered by an MIT license? Perhaps with some sort of addendum in the license like: "Contributions from @IanLee1521 aka lee1001@llnl.gov are contributed under an MIT license" ?

**Comment by konklone** [comment]
It's possible to dual-license projects or to use mixed-license code. I think the issue is really more that that defeats (some of) the purpose of using CC0 for the project, which is to give downstream users a completely and unambiguously clear copyright and attribution situation. Even one exception means that, suddenly, downstream users are technically obligated to maintain attribution for that exception, and to factor in that a bit of the code is copyrighted in any further legal or operational decisions they make. There is a practical value to having the code be 100.0% CC0-dedicated.

I also promise we're not ignoring your plight. My suggestion is that we take this up with @AlvandSalehi this week.

**Comment by IanLee1521** [comment]
Understood. It also doesn't do anything for any of the other USG CC0 projects out there either, and it would be pretty unlikely in my mind that all would be willing (or able) to dual-license.

**Comment by IanLee1521** [comment]
Since I've currently found a path to contributing through DOE / LLNL, I'm going to go ahead and close this as no longer needed.
